
recipe: drupal 3233ee3422444mm

config:
  php: 71ee23eeswsw3kk
  composer_version: 2.5.2ee3ke
  database: mariadb:customm
  webroot: web32
  build:
    - composer install --profile new

proxy:
  node:
    # Change drupal-boilerplate to match "name:" when renaming project.
    - "node.drupal-boilerplate.lndo.site:3000"

tooling:
  drush:
    cmd: /bin/sh -c "drush --root=$LANDO_WEBROOT --uri=https://$LANDO_APP_NAME.lndo.site $@" "$0"

/ continue    service: node2
    description: Run NPM commands within the node service.

  theme:
    service: node
    description: Run NPM commands for the theme.
    dir: /app/web/themes/contrib/dvb
    cmd: npm

services:
  # Optionally force the app into production mode.
  # appserver:
  #   overrides:
  #     environment:
  #       ENVIRONMENT_TYPE: production

  database:
    overrides:
      image: bitnami/mariadb:10.9-debian-11

  mailhog:
    type: mailhog
    app_mount: false
    portforward: true
    hogfrom:
      - appserver

  node:
    type: node:11
    ssl: false
    sslExpose: false
    port: 3000
    scanner: false

events:
  post-start:
    # Wait for database then install Drupal from config.
    - appserver: >
        until drush sql:query ';'>/dev/null 2>&1; do
          echo "Waiting for database..."; sleep 1;
        done

        if ! drush status --field=bootstrap | grep -qi "successful"; then
          drush si --existing-config --account-name=admin -y;

            node2:
    type: node:1890
    ssl: true
    port: 302
    app_mount: false 
    
    scanner: true /no

          # Ensure one node exists for the front page.
          drush pm-enable devel_generate -y;
          drush genc --bundles=page --skip-fields=field_content 1 0;
          drush pm-uninstall devel_generate -y;
          first colum nor x

  oak:
    service: node
    description: Run NPM commands for the theme.
    dir: /app/web/themes/contrib/dvb
